In [1]:
# Con el uso de DEAP, resolver el anterior ejercicio.
import numpy as np
import array
import random
from deap import base, creator, tools, algorithms
import pandas as pd

def evalTSP(individual):
    distance = distance_map[individual[-1]][individual[0]]
    for gene1, gene2 in zip(individual[0:-1], individual[1:]):
        distance += distance_map[gene1][gene2]
    return distance,


df= pd.read_csv(r'C:\Users\ivanj\Desktop\INF354_2do\Ejercicio 3\grafo.csv', skiprows=0, low_memory=False)

distance_map = np.array(df.values)
IND_SIZE = 5


creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
creator.create("Individual", array.array, typecode='i', fitness=creator.FitnessMin)

toolbox = base.Toolbox()

toolbox.register("indices", random.sample, range(IND_SIZE), IND_SIZE)
toolbox.register("individual", tools.initIterate, creator.Individual, toolbox.indices)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)



toolbox.register("mate", tools.cxPartialyMatched)
toolbox.register("mutate", tools.mutShuffleIndexes, indpb=0.05)
toolbox.register("select", tools.selTournament, tournsize=3)
toolbox.register("evaluate", evalTSP)

def main():
    random.seed(169)
    pop = toolbox.population(n=100)

    hof = tools.HallOfFame(1)
    stats = tools.Statistics(lambda ind: ind.fitness.values)
    stats.register("avg", np.mean)
    stats.register("std", np.std)
    stats.register("min", np.min)
    stats.register("max", np.max)
    
    algorithms.eaSimple(pop, toolbox, 0.7, 0.2, 100, stats=stats, halloffame=hof)
    
    return pop, stats, hof

if __name__ == "__main__":
    print(distance_map)
    pop,stats,hof=main()
    print(hof)
    print(evalTSP(hof[0]))

[[ 0  7  9  8 20]
 [ 7  0 10  4 11]
 [ 9 10  0 15  5]
 [ 8  4 15  0 17]
 [20 11  5 17  0]]
gen	nevals	avg 	std    	min	max
0  	100   	52.6	9.41169	37 	69 
1  	81    	50.11	8.49458	37 	69 
2  	75    	48.8 	8.923  	37 	69 
3  	73    	45.99	8.33486	37 	69 
4  	65    	46.03	9.20158	37 	69 
5  	83    	46.39	8.84522	37 	64 
6  	83    	47.45	9.34706	37 	69 
7  	80    	46.23	8.46741	37 	69 
8  	66    	44.25	7.64379	37 	60 
9  	67    	42.85	8.28176	37 	64 
10 	76    	41.8 	7.78075	37 	60 
11 	70    	40.24	7.07548	37 	60 
12 	69    	40.48	7.53456	37 	59 
13 	76    	38.87	4.62959	37 	55 
14 	73    	38.63	4.4959 	37 	55 
15 	86    	39.03	5.34126	37 	55 
16 	63    	38.35	4.02834	37 	59 
17 	73    	38.07	4.17673	37 	59 
18 	75    	37.32	2.0488 	37 	55 
19 	80    	38.33	4.39785	37 	59 
20 	71    	38.04	4.20932	37 	59 
21 	79    	38.23	4.23758	37 	55 
22 	76    	37.96	3.29521	37 	55 
23 	68    	37.28	2.04   	37 	55 
24 	79    	37.79	3.28114	37 	59 
25 	68    	37.77	3.61623	37 	59 
26 	78    	37.81	3.8